language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

sudo: false

before_install:
    - "npm config set spin false"
    - "npm install -g npm@^2"

cache:
  directories:
    - node_modules
